// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcN18bcKVBz8oAIUc9WQ8l2iK9idKUbSc',
    appId: '1:838514532607:web:168689e7e5d4e0854becca',
    messagingSenderId: '838514532607',
    projectId: 'fir-crud-c3dac',
    authDomain: 'fir-crud-c3dac.firebaseapp.com',
    storageBucket: 'fir-crud-c3dac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiutsFzFhA-c5JgtknIhas-AiqU-i9DW8',
    appId: '1:838514532607:android:d9bf2082b6a07fe04becca',
    messagingSenderId: '838514532607',
    projectId: 'fir-crud-c3dac',
    storageBucket: 'fir-crud-c3dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5d6-PBou75thKN-h98-t6sSfEg_WRxaU',
    appId: '1:838514532607:ios:9cbd360ea703f2304becca',
    messagingSenderId: '838514532607',
    projectId: 'fir-crud-c3dac',
    storageBucket: 'fir-crud-c3dac.appspot.com',
    iosBundleId: 'com.example.tugaspemrogramanmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5d6-PBou75thKN-h98-t6sSfEg_WRxaU',
    appId: '1:838514532607:ios:310a3504d7d411a74becca',
    messagingSenderId: '838514532607',
    projectId: 'fir-crud-c3dac',
    storageBucket: 'fir-crud-c3dac.appspot.com',
    iosBundleId: 'com.example.tugaspemrogramanmobile.RunnerTests',
  );
}
